baseURL = "https://faanross.com"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
pygmentsStyle = "monokai"
theme = "gokarna"



[params]

  CustomHeadHTML = """
      <script>
          (function(w,d,e,u,f,l,n){w[f]=w[f]||function(){(w[f].q=w[f].q||[])
          .push(arguments);},l=d.createElement(e),l.async=1,l.src=u,
          n=d.getElementsByTagName(e)[0],n.parentNode.insertBefore(l,n);})
          (window,document,'script','https://assets.mailerlite.com/js/universal.js','ml');
          ml('account', '1462037');
      </script>
      """

  # Choose the color shown when hyperlinks are hovered over
  accentColor = "#eb89f4"

customHeadHTML = """
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    """

  # Resource URL for the site avatar (home page and header)
  avatarURL = "/images/firestarter.png"
  avatarAltText = "firestarter"

  # Set the avatar's size: size-xs, size-s, size-m, size-l & size-xl
  avatarSize = "size-l"

  # Inject arbitrary HTML via the <head> tag
  # Best used for importing custom JavaScript, CSS, or analytics

  # Configure how post dates are displayed
  dateFormat = "January 2, 2006"
  
  # Home page meta description
  description = "| gnostic explorations in threat hunting |"

  # Footer text (i.e. author/project name)
  footer = "faan rossouw"

  # Define SEO keywords
  metaKeywords = ["faan rossouw", "command and control", "cyber security", "malware"]

  # Define how many posts are displayed on the home page
  # showPostsOnHomePage must be "popular" or "recent"
  numberPostsOnHomePage = 4

  # Display a "back to top" button on posts and pages: true, false
  # May not render on smaller screen sizes
  showBackToTopButton = true

  # Display posts on the home page:
  # "popular" (order posts by weight)
  # "recent" (order posts by date)
  # "", unset (do not display)
  showPostsOnHomePage = ""

  # Show the previous and next post in your timeline: "true", "false"
  # Incompatible with Weight
  togglePreviousAndNextButtons = "false"






